spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: yangsae.reg@gmail.com
    password: IdmftFdr09!#
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true